name: Update Football Data

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensures the full history is available

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Clone football repositories
      run: |
        git clone --depth 1 https://github.com/openfootball/deutschland.git
        git clone --depth 1 https://github.com/openfootball/italy.git
        git clone --depth 1 https://github.com/openfootball/england.git
        git clone --depth 1 https://github.com/openfootball/espana.git
        git clone --depth 1 https://github.com/openfootball/champions-league.git
        git clone --depth 1 https://github.com/openfootball/europe.git
        git clone --depth 1 https://github.com/openfootball/austria.git

    - name: Generate updated data
      run: python3 converter.py

    - name: Commit changes
      run: |
        git config --global user.email "gabale.ag@gmail.com"
        git config --global user.name "walele993"
        git add all_matches.json
        git commit -m "Update football data (automated)"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.UPDATE_FOOTBALL_CALENDAR_TOKEN }}
        title: "Update football data"
        body: "This PR updates the football data with the latest information."
        base: main
        head: update-football-data
        commit-message: "Update football data"
        delete-branch: true