name: Update Football Data

on:
  schedule:
    - cron: '0 0 * * *'  # Esecuzione giornaliera alle 00:00 UTC
  workflow_dispatch:     # Esecuzione manuale

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Clone football repositories
      run: |
        set -e
        git clone --depth 1 https://github.com/openfootball/deutschland.git
        git clone --depth 1 https://github.com/openfootball/italy.git
        git clone --depth 1 https://github.com/openfootball/england.git
        git clone --depth 1 https://github.com/openfootball/espana.git
        git clone --depth 1 https://github.com/openfootball/champions-league.git
        git clone --depth 1 https://github.com/openfootball/europe.git
        git clone --depth 1 https://github.com/openfootball/austria.git

    - name: Generate updated data
      run: python3 converter.py

    - name: Configure Git
      run: |
        git config --global user.email "meucci.gabriele1993@gmail.com"
        git config --global user.name "walele993"

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add all_matches.json
        if ! git diff --staged --quiet; then
          git commit -m "Update football data (automated)"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          echo "✅ Data updated successfully"
        else
          echo "🔄 No changes to commit"